_extends: gh-config


repository:
  name: celeritasdb
  description: A redis compatible database.
  homepage: https://blog.openacid.com/
  topics: rust, db, distributed, wan, global-consistency


labels:
  - name: smr
    color: "0d1999"
